### ISSUE TITLE
Network drive mounted

### ISSUE THREAD

**Issue by thalesmaoa** [tom-2015/imgclone#11]
Hi there, perfect project. Exactly what I was looking for, however I'm still confused.
I have 1T HD attached and auto mounted during boot `/home/user/Share`.

Can I use `imgclone` to that folder? It will exclude `/home/user/Share` from backup?

**Comment by tom-2015** [comment]
It should only copy the partitions on the SD card and skip the HD.

**Comment by thalesmaoa** [comment]
Nice. I was also wondering, is it possible to just upgrade an created image?
Let me suppose that I want to keep a daily backup, however there is no need to clone entire disk. Is there a way to just update last created img? This is more a feature request, I guess...

**Comment by tom-2015** [comment]
This is not so easy right now because the destination file (.img) is only the size of the used space on the SD card. If you add new files at some point the used space on your SD card will be bigger than the original created file size of the .img file. Expanding the file is not possible.

Maybe easy solution is to create the initial .img file with the same size as the SD card and then use rsync to synchronize all files.
You can try this with the -x parameter to add extra space in the .img file for future use.
Next time you want to create backup you can mount the .img file and use something like rsync command to update and delete changed files.

**Comment by thalesmaoa** [comment]
Thanks, I will try it. If it works I will open a PR.
